modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="villagerking"
version="${file.jarVersion}"
displayName="Epic Fight Villager King"
description='''A villager king boss with Epic Fight combat.'''

[[dependencies.villagerking]]
modId="forge"
mandatory=true
versionRange="[47.4.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.villagerking]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.villagerking]]
modId="epicfight"
mandatory=true
versionRange="[20.14.17,21)"
ordering="AFTER"
side="BOTH"
